// Permission keys the UI refers to. Mirrors the API catalog
// (tennis-backend/src/authz/permissions.ts); the API is the authority, and
// a key missing here simply can't be referenced by the UI.
export type Permission =
  | 'dashboard.global.view'
  | 'audit.view'
  | 'report.view'
  | 'report.export'
  | 'notification.broadcast'
  | 'user.view'
  | 'user.update'
  | 'user.status.manage'
  | 'user.password.reset'
  | 'user.roles.assign'
  | 'role.view'
  | 'role.manage'
  | 'access_request.review'
  | 'organization.create'
  | 'federation.view'
  | 'federation.update'
  | 'federation.clubs.view'
  | 'federation.clubs.validate'
  | 'federation.players.view'
  | 'federation.rankings.view'
  | 'club.view'
  | 'club.update'
  | 'club.dashboard.view'
  | 'court.view'
  | 'court.manage'
  | 'member.view'
  | 'member.manage'
  | 'membership.plan.manage'
  | 'booking.view'
  | 'booking.manage'
  | 'payment.view'
  | 'payment.record'
  | 'payment.refund'
  | 'tournament.view'
  | 'tournament.create'
  | 'tournament.update'
  | 'tournament.delete'
  | 'tournament.lifecycle.manage'
  | 'tournament.interrupt'
  | 'tournament.staff.manage'
  | 'tournament.announce'
  | 'registration.view'
  | 'registration.manage'
  | 'draw.view'
  | 'draw.manage'
  | 'draw.publish'
  | 'draw.modify_locked'
  | 'match.view'
  | 'match.schedule'
  | 'match.result.enter'
  | 'match.result.validate'
  | 'match.status.manage'
  | 'match.incident.report'
  | 'match.assigned_only';

/** A permission requirement: any of the list, or all of it. */
export type PermissionRule = { any: readonly Permission[] } | { all: readonly Permission[] };
